name: Github Packages CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/antyung88/wireguard

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - run: docker build . -t wireguard
      - run: curl -L -O https://downloads.dockerslim.com/releases/1.37.3/dist_linux.tar.gz
      - run: tar -zxvf dist_linux.tar.gz
      - run: script -q -c "./dist_linux/docker-slim --debug version"
      - run: script -q -c "./dist_linux/docker-slim build --target wireguard --http-probe-off --include-path /config --tag ghcr.io/antyung88/wireguard.slim"
      
      - name: Push
        run: |
          docker push ghcr.io/antyung88/wireguard.slim
